<?php
// $Id: currency_converter.module,v 1.1 2011/02/13 13:00:06 spleshka Exp $ 

/**
  * Implementation of hook_menu()
  */  
  
function currency_converter_menu() {

  $items['admin/settings/currency_converter'] = array(
    'title' => 'Currency converter',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('currency_converter_admin_settings', NULL),
    'access arguments' => array('administer content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'currency_converter.admin.inc',
  );

  return $items;
}

/**
  * Implementation of hook_block()
  */ 
  
function currency_converter_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
  
    case 'list':

      $block[0]['info'] = t('Currency converter');
      $block[0]['cache'] = BLOCK_CACHE_GLOBAL;
  
      return $block;
  
    case 'view':      
        
      $use_css = variable_get('currency_converter_use_css', 1);
      if ($use_css)    
        drupal_add_css(drupal_get_path('module', 'currency_converter') .'/css/currency_converter.css');      

      $use_bg = variable_get('currency_converter_use_bg', 1);
      if ($use_bg)    
        drupal_add_css(drupal_get_path('module', 'currency_converter') .'/css/currency_converter_bg.css');
      
      drupal_add_js(drupal_get_path('module', 'currency_converter') .'/currency_converter.js');
  
      $block['subject'] = t('Converter');
      $block['content'] =  drupal_get_form('currency_converter_block_form');
  
      return $block;
    }
}

/**
  * Implementation of hook_cron()
  */ 
  
function currency_converter_cron() {

  $time = time();

  //Belorussian bank
  $xmlstr = file_get_contents('http://www.priorbank.by/CurratesExportXml.axd?channel=1&iso={{iso}}&code={{code}}&from={{from}}&to={{to}}' );
  
  if ($xmlstr) {
    $xml = new SimpleXMLElement($xmlstr);
  
    foreach ($xml->LIST_R_DATE->R_DATE->LIST_E_CHANNEL->E_CHANNEL->LIST_RATE->RATE as $rate) {

      if ($rate->ISO == 'RUB')
        $rub = number_format((float)$rate->BUY, 2, '.', '');

      if ($rate->ISO == 'EUR')
        $eur = number_format((float)$rate->BUY, 2, '.', '');

      if ($rate->ISO == 'USD')
        $usd = number_format((float)$rate->BUY, 2, '.', '');

      if ($rate->ISO == 'CAD')
        $cad = number_format((float)$rate->BUY, 2, '.', '');

      if ($rate->ISO == 'PLN')
        $pln = number_format((float)$rate->BUY, 2, '.', '');

      if ($rate->ISO == 'UAH')
        $uah = number_format((float)$rate->BUY, 2, '.', '');

      if ($rate->ISO == 'CNY')
        $cny = number_format((float)$rate->BUY, 2, '.', '');

      if ($rate->ISO == 'LTL')
        $ltl = number_format((float)$rate->BUY, 2, '.', '');

      if ($rate->ISO == 'LVL')
        $lvl = number_format((float)$rate->BUY, 2, '.', '');

    }

    $check = db_fetch_object(db_query_range('SELECT * FROM {currency_converter} WHERE conv_type = 0', 0, 1));

    if ($check) {
      db_query("
        UPDATE {currency_converter} 
        SET rub = %f, eur = %f, usd = %f, cad = %f, pln = %f, uah = %f, cny = %f, ltl = %f, lvl = %f, timestamp = %d WHERE conv_type = 0",
        $rub, $eur, $usd, $cad, $pln, $uah, $cny, $ltl, $lvl, $time
      );  
    }
    else {
      $signature = array(
        'создание сайта', 'продвижение сайта', 'создание сайтов', 'продвижение сайтов', 'создание полезных виджетов в интернете', 
        'seo', 'раскрутка сайтов', 'раскрутка сайта', 'реклама в интернете'
      );
      $signature_selected = $signature[rand(0, 8)];
      db_query("
        INSERT INTO {currency_converter} (conv_type, byr, rub, eur, usd, cad, pln, uah, cny, ltl, lvl, timestamp, signature) 
        values (0, 0, %f, %f, %f, %f, %f, %f, %f, %f, %f, %d, '%s')",
        $rub, $eur, $usd, $cad, $pln, $uah, $cny, $ltl, $lvl, $time, $signature_selected
      );  
    }  
  }

  //Russian bank 
  $xmlstr=file_get_contents('http://www.cbr.ru/scripts/XML_daily.asp' );
  
  if ($xmlstr) {
  
    $xml=new SimpleXMLElement($xmlstr);
  
    foreach ($xml->Valute as $rate) {

      if ($rate->CharCode == 'BYR')
        $byr = number_format(str_replace(',' , '.', $rate->Value ) / $rate->Nominal , 4, '.', '');

      if ($rate->CharCode == 'EUR') 
        $eur = number_format(str_replace(',' , '.', $rate->Value ) / $rate->Nominal , 4, '.', '');

      if ($rate->CharCode == 'USD')
        $usd = number_format(str_replace(',' , '.', $rate->Value ) / $rate->Nominal , 4, '.', '');

      if ($rate->CharCode == 'CAD')
        $cad = number_format(str_replace(',' , '.', $rate->Value ) / $rate->Nominal , 4, '.', '');

      if ($rate->CharCode == 'PLN')
        $pln = number_format(str_replace(',' , '.', $rate->Value ) / $rate->Nominal , 4, '.', '');

      if ($rate->CharCode == 'UAH')
        $uah = number_format(str_replace(',' , '.', $rate->Value ) / $rate->Nominal , 4, '.', '');
 
      if ($rate->CharCode == 'CNY')
        $cny = number_format(str_replace(',' , '.', $rate->Value ) / $rate->Nominal , 4, '.', '');

      if ($rate->CharCode == 'LTL')
        $ltl = number_format(str_replace(',' , '.', $rate->Value ) / $rate->Nominal , 4, '.', '');

      if ($rate->CharCode == 'LVL')
        $lvl = number_format(str_replace(',' , '.', $rate->Value ) / $rate->Nominal , 4, '.', '');

    }
  
    $check = db_fetch_object(db_query_range('SELECT * FROM {currency_converter} WHERE conv_type = 1', 0, 1));

    if ($check) {
      db_query(
        "UPDATE {currency_converter} 
        SET byr = %f, eur = %f, usd = %f, cad = %f, pln = %f, uah = %f, cny = %f, ltl = %f, lvl = %f, timestamp = %d  WHERE conv_type = 1",
        $byr, $eur, $usd, $cad, $pln, $uah, $cny, $ltl, $lvl, $time
      );  
    }
    else {
      $signature = array(
        'создание сайта', 'продвижение сайта', 'создание сайтов', 'продвижение сайтов', 'создание полезных виджетов в интернете', 
        'seo', 'раскрутка сайтов', 'раскрутка сайта', 'реклама в интернете'
      );
      $signature_selected = $signature[rand(0, 8)];

      db_query("
        INSERT INTO {currency_converter} (conv_type, byr, rub, eur, usd, cad, pln, uah, cny, ltl, lvl, timestamp, signature) 
        values (1, %f, 0, %f, %f, %f, %f, %f, %f, %f, %f, %d, '%s')",
        $byr, $eur, $usd, $cad, $pln, $uah, $cny, $ltl, $lvl, $time, $signature_selected
      );  
    }
  }
  
}

/**
 * Implementation of hook_theme().
 */
function currency_converter_theme($existing, $type, $theme, $path) {

  return array(
  
    'currency_converter_block_form' => array(
      'arguments' => array('form' => NULL),
      'template' => 'currency_converter',
    ),

    'currency_converter_admin_settings' => array(
      'arguments' => array('form' => NULL),
    ),

  );
}

/**
 * Process variables for currency_converter.tpl.php.
 *
 * The $variables array contains the following arguments:
 * - $form
 *
 * @see currency_converter.tpl.php
 */
function template_preprocess_currency_converter_block_form(&$variables) {

  $val = db_fetch_object(db_query_range('SELECT timestamp, signature FROM {currency_converter}', 0, 1));
  
  if ($val) {
    $bank = variable_get('currency_converter_bank_default', '0');
    if ($bank == '0') 
      $from = t('From NBB');  
    else 
      $from = t('From RCB');  
  
    $variables['time'] = $from .' '. date('d.m.Y', $val->timestamp);
    $variables['body'] = drupal_render($variables['form']);
    $variables['developers'] = '<a href = "http://www.internet-marketing.by/" alt = "'. $val->signature .'" class = "dev" ></a>';
  }
}


function currency_converter_block_form() {

  $currencies = array('BYR', 'RUB', 'EUR', 'USD', 'CAD', 'PLN', 'UAH', 'CNY', 'LTL', 'LVL');
  
  $default_currency = variable_get('currency_converter_main_currency', 'BYR');
  $currency_types_enabled = variable_get('currency_converter_currency_types', array('BYR', 'RUB', 'EUR', 'USD', 'CAD', 'PLN', 'UAH', 'CNY', 'LTL', 'LVL'));
  $currency_weight = variable_get('currency_converter_weight', '');
  $bank = variable_get('currency_converter_bank_default', 0);
  
  $currencies_values = db_fetch_array(db_query_range('SELECT * FROM {currency_converter} WHERE conv_type = %d', $bank, 0, 1));

  if ($currencies_values) {
  
    $default_value = $currencies_values[strtolower($default_currency)] ? $currencies_values[strtolower($default_currency)] : '1';
  
    $form[$default_currency] = array(
      '#weight' => -11,
      '#prefix' => '<div class = "'. strtolower($default_currency) .'">',
      '#suffix' => '</div>',
    );
  
    $form[$default_currency]['value'] = array(
      '#type' => 'item',
      '#title' => $default_currency,
      '#value' => '<span></span>',
    );
  
    $form[$default_currency]['input'] = array(
      '#type' => 'textfield',
      '#size' => 10,
      '#attributes' => array('class' => 'active'),
    );
  
    foreach ($currency_types_enabled as $currency) {

      if ($currency != $default_currency) {
  
        $value = $currencies_values[strtolower($currency)] ? $currencies_values[strtolower($currency)] : '1';
        $value = $value / $default_value;
        $value = (int)$value >= 100 ? number_format($value, 2, '.', '') : number_format($value, 4, '.', '');

        $weight = $currency_weight[$currency];   
  
        $form[$currency] = array(
          '#weight' => $weight,
          '#prefix' => '<div class = "'. strtolower($currency) .'">',
          '#suffix' => '</div>',
        );
  
        $form[$currency]['value'] = array(
          '#type' => 'item',
          '#title' => $currency,
          '#value' => '<span>'. $value .'</span>',
        );
  
        $form[$currency]['input'] = array(
          '#type' => 'textfield',
          '#size' => 10,
        );		
      }    
    }

  }
  else  
    drupal_set_message(t('Please, run cron to enable the Currency converter module'), 'warning');
  
  return $form;
}